spring:
  datasource:
    username: root
    password: 1993315zxy
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80

# 整合mybatis
# classpath就是指代resources目录
mybatis:
  type-aliases-package: com.app.pojo
  mapper-locations: classpath:mybatis/*.xml